local DbOption = require("Options.DbOption")

return {
	isEnabled = DbOption.new():setValue(true):checkbox(),
	lockUIPosition = DbOption.new():setValue(false):checkbox(),
	username = DbOption.new():setValue(""):editbox(),
	oauth = DbOption.new():setValue(""):editbox(),
	clientId = DbOption.new():setValue(""):editbox(),
	showUserTags = DbOption.new():setValue(true):checkbox(),
	showTimestamps = DbOption.new():setValue(true):checkbox(),
	showViewerCount = DbOption.new():setValue(true):checkbox(),
	showRaids = DbOption.new():setValue(true):checkbox(),
	showFollows = DbOption.new():setValue(true):checkbox(),
	showSubscribers = DbOption.new():setValue(true):checkbox(),
	showBits = DbOption.new():setValue(true):checkbox(),
	showCharity = DbOption.new():setValue(true):checkbox(),
	colorSelection = DbOption.new():setValue("twitch"):combo({
		DbOption.Item(_("Twitch")):Value("twitch"),
		DbOption.Item(_("Palette")):Value("palette"),
	}),
	fontSize = DbOption.new():setValue(14):slider(DbOption.Range(10, 18)),
	hideInactiveTimer = DbOption.new():setValue(0):combo({
		DbOption.Item(_("Never")):Value(0),
		DbOption.Item(_("30 seconds")):Value(0.5),
		DbOption.Item(_("1 min")):Value(1),
		DbOption.Item(_("2 min")):Value(2),
		DbOption.Item(_("5 min")):Value(5),
		DbOption.Item(_("10 min")):Value(10),
		DbOption.Item(_("30 min")):Value(30),
		DbOption.Item(_("60 min")):Value(60),
	}),
	hideShowHotkey = DbOption.new():setValue("Ctrl+Shift+."):combo({
		DbOption.Item(_("Ctrl+Shift+.")):Value("Ctrl+Shift+."),
		DbOption.Item(_("NumPad .")):Value("[.]"),
		DbOption.Item(_("NumPad -")):Value("[-]"),
		DbOption.Item(_("NumPad /")):Value("[/]"),
		DbOption.Item(_("NumPad *")):Value("[*]"),
		DbOption.Item(_("NumPad +")):Value("[+]"),
		DbOption.Item(_("NumPad 0")):Value("[0]"),
		DbOption.Item(_("NumPad 1")):Value("[1]"),
		DbOption.Item(_("NumPad 2")):Value("[2]"),
		DbOption.Item(_("NumPad 3")):Value("[3]"),
		DbOption.Item(_("NumPad 4")):Value("[4]"),
		DbOption.Item(_("NumPad 5")):Value("[5]"),
		DbOption.Item(_("NumPad 6")):Value("[6]"),
		DbOption.Item(_("NumPad 7")):Value("[7]"),
		DbOption.Item(_("NumPad 8")):Value("[8]"),
		DbOption.Item(_("NumPad 9")):Value("[9]"),
		DbOption.Item(_("0")):Value("0"),
		DbOption.Item(_("1")):Value("1"),
		DbOption.Item(_("2")):Value("2"),
		DbOption.Item(_("3")):Value("3"),
		DbOption.Item(_("4")):Value("4"),
		DbOption.Item(_("5")):Value("5"),
		DbOption.Item(_("6")):Value("6"),
		DbOption.Item(_("7")):Value("7"),
		DbOption.Item(_("8")):Value("8"),
		DbOption.Item(_("9")):Value("9"),
	}),
}