local emojis = {
	-- 3-BYTE
	["™"] = ":trademark:", ["€"] = ":euro:", ["₹"] = ":rupee:", ["≠"] = ":not-equal:", ["≈"] = ":approximate:",
	["≤"] = ":leq:", ["≥"] = ":geq:", ["∞"] = ":infinity:", ["√"] = ":squareroot:", ["∑"] = ":sum:",
	["♥"] = ":hearts:", ["♦"] = ":diamonds:", ["♠"] = ":spades:", ["★"] = ":star:", ["☆"] = ":star:",
	["→"] = ":arrow_right:", ["←"] = ":arrow_left:", ["↑"] = ":arrow_up:", ["↓"] = ":arrow_down:", ["↔"] = ":arrow_leftright:",
	["•"] = ":bulletpoint:", ["♪"] = ":music:", ["♫"] = ":music:", ["⇒"] = ":implies:", ["✓"] = ":checkmark:",
	["✔"] = ":checkmark:", ["✕"] = ":x:", ["✖"] = ":x:", ["❌"] = ":x:", ["✅"] = ":white_check_mark:",
	["☑"] = ":ballot_box_with_check:", ["⚠"] = ":warning:", ["❗"] = ":exclamation:", ["❓"] = ":question:", ["✨"] = ":sparkles:",
	["⭐"] = ":star:", ["⚡"] = ":zap:", ["☀"] = ":sun:", ["☁"] = ":cloud:", ["❄"] = ":snowflake:",
	["☂"] = ":umbrella:", ["❤"] = ":heart:", ["❎"] = ":negative_squared_cross_mark:", ["➕"] = ":heavy_plus_sign:", ["➖"] = ":heavy_minus_sign:",
	["➗"] = ":heavy_division_sign:", ["➰"] = ":curly_loop:", ["➿"] = ":double_curly_loop:",

	-- 4-BYTE
	-- FACES
	["😀"] = ":grinning:", ["😃"] = ":smiley:", ["😄"] = ":smile:", ["😁"] = ":grin:", ["😆"] = ":laughing:",
	["😅"] = ":sweat_smile:", ["😂"] = ":joy:", ["🤣"] = ":rofl:", ["🥲"] = ":smiling_face_with_tear:", ["🥹"] = ":face_holding_back_tears:",
	["😊"] = ":blush:", ["😇"] = ":innocent:", ["🙂"] = ":slight_smile:", ["🙃"] = ":upside_down:", ["😉"] = ":wink:",
	["😌"] = ":relieved:", ["😍"] = ":heart_eyes:", ["🥰"] = ":smiling_face_with_hearts:", ["😘"] = ":kissing_heart:", ["😗"] = ":kissing:",
	["😙"] = ":kissing_smiling_eyes:", ["😚"] = ":kissing_closed_eyes:", ["😋"] = ":yum:", ["😛"] = ":stuck_out_tongue:", ["😜"] = ":stuck_out_tongue_winking_eye:",
	["🤪"] = ":zany_face:", ["😝"] = ":stuck_out_tongue_closed_eyes:", ["🤗"] = ":hugging:", ["🥳"] = ":partying:", ["😎"] = ":sunglasses:",
	["🤩"] = ":star_struck:", ["🥸"] = ":disguised_face:", ["😏"] = ":smirk:", ["😐"] = ":neutral_face:", ["😑"] = ":expressionless:",
	["😶"] = ":no_mouth:", ["😒"] = ":unamused:", ["🙄"] = ":roll_eyes:", ["😬"] = ":grimacing:", ["😕"] = ":confused:",
	["😟"] = ":worried:", ["🙁"] = ":slightly_frowning:", ["☹️"] = ":frowning:", ["😮"] = ":open_mouth:", ["😯"] = ":hushed:",
	["😲"] = ":astonished:", ["😳"] = ":flushed:", ["🥺"] = ":pleading:", ["😢"] = ":cry:", ["😭"] = ":sob:",
	["😱"] = ":scream:", ["😖"] = ":confounded:", ["😣"] = ":persevere:", ["😞"] = ":disappointed:", ["😓"] = ":sweat:",
	["😩"] = ":weary:", ["😫"] = ":tired_face:", ["🥱"] = ":yawning:", ["😤"] = ":triumph:", ["😡"] = ":rage:",
	["😠"] = ":angry:", ["🤑"] = ":money_mouth_face:", ["🤢"] = ":nauseated_face:", ["😴"] = ":sleeping:", ["🤤"] = ":drooling_face:",
	["🤮"] = ":face_vomiting:", ["🤯"] = ":exploding_head:", ["🤠"] = ":cowboy_hat_face:", ["😈"] = ":smiling_face_with_horns:", ["👿"] = ":angry_face_with_horns:",
	["🤓"] = ":nerd_face:", ["🧐"] = ":face_with_monocle:", ["🤫"] = ":shushing_face:", ["🤬"] = ":face_with_symbols_on_mouth:", ["😨"] = ":fearful:",
	["😰"] = ":cold_sweat:", ["😥"] = ":disappointed_relieved:", ["🤭"] = ":face_with_hand_over_mouth:", ["🤔"] = ":thinking:", ["🤐"] = ":zipper_mouth_face:",
	["🤨"] = ":face_with_raised_eyebrow:", ["🫠"] = ":melting_face:", ["🫢"] = ":face_with_open_eyes_and_hand_over_mouth:", ["🫣"] = ":face_with_peeking_eye:", ["🫡"] = ":saluting_face:",
	["🫥"] = ":dotted_line_face:", ["🫤"] = ":face_with_diagonal_mouth:", ["🥴"] = ":woozy_face:", ["😵"] = ":dizzy_face:", ["😷"] = ":mask:",
	["🤒"] = ":face_with_thermometer:", ["🤕"] = ":face_with_head_bandage:", ["🤧"] = ":sneezing_face:", ["🥵"] = ":hot_face:", ["🥶"] = ":cold_face:",
	["🤡"] = ":clown_face:", ["🤥"] = ":lying_face:", ["😔"] = ":pensive:", ["😪"] = ":sleepy:",

	-- ANIMALS
	["🐶"] = ":dog:", ["🐱"] = ":cat:", ["🐍"] = ":snake:", ["🐐"] = ":goat:",

	-- GESTURES
	["👋"] = ":wave:", ["🤚"] = ":raised_back_of_hand:", ["✋"] = ":raised_hand:", ["🖖"] = ":vulcan_salute:", ["👌"] = ":ok_hand:",
	["🤏"] = ":pinching_hand:", ["🤞"] = ":crossed_fingers:", ["🤟"] = ":love_you_gesture:", ["🤘"] = ":sign_of_the_horns:", ["🤙"] = ":call_me_hand:",
	["👈"] = ":point_left:", ["👉"] = ":point_right:", ["👆"] = ":point_up_2:", ["🖕"] = ":middle_finger:", ["👇"] = ":point_down:",
	["👍"] = ":thumbsup:", ["👎"] = ":thumbsdown:", ["✊"] = ":fist:", ["👊"] = ":fist_oncoming:", ["🤛"] = ":left_facing_fist:",
	["🤜"] = ":right_facing_fist:", ["👏"] = ":clap:", ["🙌"] = ":raised_hands:", ["👐"] = ":open_hands:", ["🤲"] = ":palms_up_together:",
	["🤝"] = ":handshake:", ["🙏"] = ":pray:",

	-- EMOTIONS
	["🧡"] = ":orange_heart:", ["💛"] = ":yellow_heart:", ["💚"] = ":green_heart:", ["💙"] = ":blue_heart:", ["💜"] = ":purple_heart:",
	["🖤"] = ":black_heart:", ["🤍"] = ":white_heart:", ["💔"] = ":broken_heart:", ["💕"] = ":two_hearts:", ["💞"] = ":revolving_hearts:",
	["💓"] = ":heartbeat:", ["💗"] = ":heartpulse:", ["💖"] = ":sparkling_heart:", ["💘"] = ":cupid:", ["💝"] = ":gift_heart:",
	["💯"] = ":100:", ["🔥"] = ":fire:", ["🍎"] = ":apple:", ["💎"] = ":gem:", ["🌟"] = ":star2:",

	-- 5-BYTE / 6-BYTE
	["©️"] = ":copyright:", ["®️"] = ":registered:", ["✔️"] = ":checkmark:", ["❌️"] = ":x:", ["☑️"] = ":ballot_box_with_check:",
	["⚠️"] = ":warning:", ["✳️"] = ":eight_spoked_asterisk:", ["✴️"] = ":eight_pointed_star:", ["❇️"] = ":sparkle:", ["‼️"] = ":bangbang:",
	["⁉️"] = ":interrobang:", ["❤️"] = ":heart:", ["❣️"] = ":heart_exclamation:", ["✒️"] = ":black_nib:", ["✏️"] = ":pencil2:",
	["✍️"] = ":writing_hand:", ["☀️"] = ":sunny:", ["☁️"] = ":cloud:", ["☂️"] = ":umbrella:", ["☃️"] = ":snowman:",
	["☹️"] = ":frowning:", ["✌️"] = ":victory_hand:", ["☝️"] = ":point_up:", ["🖐️"] = ":raised_hand_with_fingers_splayed:", ["🕷️"] = ":spider:",
	["🕊️"] = ":dove:",

	-- 7-BYTE
	["0️⃣"] = ":zero:", ["1️⃣"] = ":one:", ["2️⃣"] = ":two:", ["3️⃣"] = ":three:", ["4️⃣"] = ":four:",
	["5️⃣"] = ":five:", ["6️⃣"] = ":six:", ["7️⃣"] = ":seven:", ["8️⃣"] = ":eight:", ["9️⃣"] = ":nine:",
	["🔟"] = ":ten:", ["#️⃣"] = ":hash:", ["*️⃣"] = ":asterisk:",

	-- MULTI-BYTE
	["😶‍🌫️"] = ":face_in_clouds:", ["😮‍💨"] = ":face_exhaling:", ["😵‍💫"] = ":face_with_spiral_eyes:",

	-- FLAGS WORLD
	["🇦🇨"] = ":ascension_island:", ["🇦🇩"] = ":andorra:", ["🇦🇪"] = ":united_arab_emirates:", ["🇦🇫"] = ":afghanistan:", ["🇦🇬"] = ":antigua_barbuda:",
	["🇦🇮"] = ":anguilla:", ["🇦🇱"] = ":albania:", ["🇦🇲"] = ":armenia:", ["🇦🇴"] = ":angola:", ["🇦🇶"] = ":antarctica:",
	["🇦🇷"] = ":argentina:", ["🇦🇸"] = ":american_samoa:", ["🇦🇹"] = ":austria:", ["🇦🇺"] = ":australia:", ["🇦🇼"] = ":aruba:",
	["🇦🇽"] = ":aland_islands:", ["🇦🇿"] = ":azerbaijan:", ["🇧🇦"] = ":bosnia_herzegovina:", ["🇧🇧"] = ":barbados:", ["🇧🇩"] = ":bangladesh:",
	["🇧🇪"] = ":belgium:", ["🇧🇫"] = ":burkina_faso:", ["🇧🇬"] = ":bulgaria:", ["🇧🇭"] = ":bahrain:", ["🇧🇮"] = ":burundi:",
	["🇧🇯"] = ":benin:", ["🇧🇱"] = ":saint_barthelemy:", ["🇧🇲"] = ":bermuda:", ["🇧🇳"] = ":brunei:", ["🇧🇴"] = ":bolivia:",
	["🇧🇶"] = ":caribbean_netherlands:", ["🇧🇷"] = ":brazil:", ["🇧🇸"] = ":bahamas:", ["🇧🇹"] = ":bhutan:", ["🇧🇻"] = ":bouvet_island:",
	["🇧🇼"] = ":botswana:", ["🇧🇾"] = ":belarus:", ["🇧🇿"] = ":belize:", ["🇨🇦"] = ":canada:", ["🇨🇨"] = ":cocos_islands:",
	["🇨🇩"] = ":congo_kinshasa:", ["🇨🇫"] = ":central_african_republic:", ["🇨🇬"] = ":congo_brazzaville:", ["🇨🇭"] = ":switzerland:", ["🇨🇮"] = ":cote_divoire:",
	["🇨🇰"] = ":cook_islands:", ["🇨🇱"] = ":chile:", ["🇨🇲"] = ":cameroon:", ["🇨🇳"] = ":china:", ["🇨🇴"] = ":colombia:",
	["🇨🇵"] = ":clipperton_island:", ["🇨🇷"] = ":costa_rica:", ["🇨🇺"] = ":cuba:", ["🇨🇻"] = ":cape_verde:", ["🇨🇼"] = ":curacao:",
	["🇨🇽"] = ":christmas_island:", ["🇨🇾"] = ":cyprus:", ["🇨🇿"] = ":czech_republic:", ["🇩🇪"] = ":germany:", ["🇩🇬"] = ":diego_garcia:",
	["🇩🇯"] = ":djibouti:", ["🇩🇰"] = ":denmark:", ["🇩🇲"] = ":dominica:", ["🇩🇴"] = ":dominican_republic:", ["🇩🇿"] = ":algeria:",
	["🇪🇦"] = ":ceuta_melilla:", ["🇪🇨"] = ":ecuador:", ["🇪🇪"] = ":estonia:", ["🇪🇬"] = ":egypt:", ["🇪🇭"] = ":western_sahara:",
	["🇪🇷"] = ":eritrea:", ["🇪🇸"] = ":spain:", ["🇪🇹"] = ":ethiopia:", ["🇪🇺"] = ":european_union:", ["🇫🇮"] = ":finland:",
	["🇫🇯"] = ":fiji:", ["🇫🇰"] = ":falkland_islands:", ["🇫🇲"] = ":micronesia:", ["🇫🇴"] = ":faroe_islands:", ["🇫🇷"] = ":france:",
	["🇬🇦"] = ":gabon:", ["🇬🇧"] = ":united_kingdom:", ["🇬🇩"] = ":grenada:", ["🇬🇪"] = ":georgia:", ["🇬🇫"] = ":french_guiana:",
	["🇬🇬"] = ":guernsey:", ["🇬🇭"] = ":ghana:", ["🇬🇮"] = ":gibraltar:", ["🇬🇱"] = ":greenland:", ["🇬🇲"] = ":gambia:",
	["🇬🇳"] = ":guinea:", ["🇬🇵"] = ":guadeloupe:", ["🇬🇶"] = ":equatorial_guinea:", ["🇬🇷"] = ":greece:", ["🇬🇸"] = ":south_georgia_south_sandwich_islands:",
	["🇬🇹"] = ":guatemala:", ["🇬🇺"] = ":guam:", ["🇬🇼"] = ":guinea_bissau:", ["🇬🇾"] = ":guyana:", ["🇭🇰"] = ":hong_kong:",
	["🇭🇲"] = ":heard_mcdonald_islands:", ["🇭🇳"] = ":honduras:", ["🇭🇷"] = ":croatia:", ["🇭🇹"] = ":haiti:", ["🇭🇺"] = ":hungary:",
	["🇮🇨"] = ":canary_islands:", ["🇮🇩"] = ":indonesia:", ["🇮🇪"] = ":ireland:", ["🇮🇱"] = ":israel:", ["🇮🇲"] = ":isle_of_man:",
	["🇮🇳"] = ":india:", ["🇮🇴"] = ":british_indian_ocean_territory:", ["🇮🇶"] = ":iraq:", ["🇮🇷"] = ":iran:", ["🇮🇸"] = ":iceland:",
	["🇮🇹"] = ":italy:", ["🇯🇪"] = ":jersey:", ["🇯🇲"] = ":jamaica:", ["🇯🇴"] = ":jordan:", ["🇯🇵"] = ":japan:",
	["🇰🇪"] = ":kenya:", ["🇰🇬"] = ":kyrgyzstan:", ["🇰🇭"] = ":cambodia:", ["🇰🇮"] = ":kiribati:", ["🇰🇲"] = ":comoros:",
	["🇰🇳"] = ":saint_kitts_nevis:", ["🇰🇵"] = ":north_korea:", ["🇰🇷"] = ":south_korea:", ["🇰🇼"] = ":kuwait:", ["🇰🇾"] = ":cayman_islands:",
	["🇰🇿"] = ":kazakhstan:", ["🇱🇦"] = ":laos:", ["🇱🇧"] = ":lebanon:", ["🇱🇨"] = ":saint_lucia:", ["🇱🇮"] = ":liechtenstein:",
	["🇱🇰"] = ":sri_lanka:", ["🇱🇷"] = ":liberia:", ["🇱🇸"] = ":lesotho:", ["🇱🇹"] = ":lithuania:", ["🇱🇺"] = ":luxembourg:",
	["🇱🇻"] = ":latvia:", ["🇱🇾"] = ":libya:", ["🇲🇦"] = ":morocco:", ["🇲🇨"] = ":monaco:", ["🇲🇩"] = ":moldova:",
	["🇲🇪"] = ":montenegro:", ["🇲🇫"] = ":saint_martin:", ["🇲🇬"] = ":madagascar:", ["🇲🇭"] = ":marshall_islands:", ["🇲🇰"] = ":north_macedonia:",
	["🇲🇱"] = ":mali:", ["🇲🇲"] = ":myanmar:", ["🇲🇳"] = ":mongolia:", ["🇲🇴"] = ":macau:", ["🇲🇵"] = ":northern_mariana_islands:",
	["🇲🇶"] = ":martinique:", ["🇲🇷"] = ":mauritania:", ["🇲🇸"] = ":montserrat:", ["🇲🇹"] = ":malta:", ["🇲🇺"] = ":mauritius:",
	["🇲🇻"] = ":maldives:", ["🇲🇼"] = ":malawi:", ["🇲🇽"] = ":mexico:", ["🇲🇾"] = ":malaysia:", ["🇲🇿"] = ":mozambique:",
	["🇳🇦"] = ":namibia:", ["🇳🇨"] = ":new_caledonia:", ["🇳🇪"] = ":niger:", ["🇳🇫"] = ":norfolk_island:", ["🇳🇬"] = ":nigeria:",
	["🇳🇮"] = ":nicaragua:", ["🇳🇱"] = ":netherlands:", ["🇳🇴"] = ":norway:", ["🇳🇵"] = ":nepal:", ["🇳🇷"] = ":nauru:",
	["🇳🇺"] = ":niue:", ["🇳🇿"] = ":new_zealand:", ["🇴🇲"] = ":oman:", ["🇵🇦"] = ":panama:", ["🇵🇪"] = ":peru:",
	["🇵🇫"] = ":french_polynesia:", ["🇵🇬"] = ":papua_new_guinea:", ["🇵🇭"] = ":philippines:", ["🇵🇰"] = ":pakistan:", ["🇵🇱"] = ":poland:",
	["🇵🇲"] = ":saint_pierre_miquelon:", ["🇵🇳"] = ":pitcairn_islands:", ["🇵🇷"] = ":puerto_rico:", ["🇵🇸"] = ":palestinian_territories:", ["🇵🇹"] = ":portugal:",
	["🇵🇼"] = ":palau:", ["🇵🇾"] = ":paraguay:", ["🇶🇦"] = ":qatar:", ["🇷🇪"] = ":reunion:", ["🇷🇴"] = ":romania:",
	["🇷🇸"] = ":serbia:", ["🇷🇺"] = ":russia:", ["🇷🇼"] = ":rwanda:", ["🇸🇦"] = ":saudi_arabia:", ["🇸🇧"] = ":solomon_islands:",
	["🇸🇨"] = ":seychelles:", ["🇸🇩"] = ":sudan:", ["🇸🇪"] = ":sweden:", ["🇸🇬"] = ":singapore:", ["🇸🇭"] = ":saint_helena:",
	["🇸🇮"] = ":slovenia:", ["🇸🇯"] = ":svalbard_jan_mayen:", ["🇸🇰"] = ":slovakia:", ["🇸🇱"] = ":sierra_leone:", ["🇸🇲"] = ":san_marino:",
	["🇸🇳"] = ":senegal:", ["🇸🇴"] = ":somalia:", ["🇸🇷"] = ":suriname:", ["🇸🇸"] = ":south_sudan:", ["🇸🇹"] = ":sao_tome_principe:",
	["🇸🇻"] = ":el_salvador:", ["🇸🇽"] = ":sint_maarten:", ["🇸🇾"] = ":syria:", ["🇸🇿"] = ":eswatini:", ["🇹🇦"] = ":tristan_da_cunha:",
	["🇹🇨"] = ":turks_caicos_islands:", ["🇹🇩"] = ":chad:", ["🇹🇫"] = ":french_southern_territories:", ["🇹🇬"] = ":togo:", ["🇹🇭"] = ":thailand:",
	["🇹🇯"] = ":tajikistan:", ["🇹🇰"] = ":tokelau:", ["🇹🇱"] = ":timor_leste:", ["🇹🇲"] = ":turkmenistan:", ["🇹🇳"] = ":tunisia:",
	["🇹🇴"] = ":tonga:", ["🇹🇹"] = ":trinidad_tobago:", ["🇹🇻"] = ":tuvalu:", ["🇹🇼"] = ":taiwan:", ["🇹🇿"] = ":tanzania:",
	["🇺🇦"] = ":ukraine:", ["🇺🇬"] = ":uganda:", ["🇺🇲"] = ":us_outlying_islands:", ["🇺🇳"] = ":united_nations:", ["🇺🇸"] = ":usa:",
	["🇺🇾"] = ":uruguay:", ["🇺🇿"] = ":uzbekistan:", ["🇻🇦"] = ":vatican_city:", ["🇻🇨"] = ":saint_vincent_grenadines:", ["🇻🇪"] = ":venezuela:",
	["🇻🇬"] = ":british_virgin_islands:", ["🇻🇮"] = ":us_virgin_islands:", ["🇻🇳"] = ":vietnam:", ["🇻🇺"] = ":vanuatu:", ["🇼🇫"] = ":wallis_futuna:",
	["🇼🇸"] = ":samoa:", ["🇽🇰"] = ":kosovo:", ["🇾🇪"] = ":yemen:", ["🇾🇹"] = ":mayotte:", ["🇿🇦"] = ":south_africa:",
	["🇿🇲"] = ":zambia:", ["🇿🇼"] = ":zimbabwe:",

	-- FLAGS OTHER
	["🏴‍☠️"] = ":pirate_flag:", ["🏁"] = ":checkered_flag:", ["🏳️‍🌈"] = ":rainbow_flag:", ["🏳️‍⚧️"] = ":transgender_flag:", ["🚩"] = ":triangular_flag:",
	["🏳️"] = ":white_flag:", ["🏴"] = ":black_flag:",
}

return emojis